#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 170266-web-01 100.25.194.52:80
        server 170266-web-02 54.227.200.149:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
